"""
Tax Doctrine Cache - Fast Expert Response Layer
Pre-compiled audit-defense doctrine for instant retrieval

Architecture:
- Doctrine-first: Pre-cached expert reasoning, not raw documents
- Single lookup: One semantic match, immediate answer
- Fallback: Full RAG only if doctrine miss

Author: ECHO OMEGA PRIME
Authority: 11.0 SOVEREIGN
"""

from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass
import re

@dataclass
class DoctrineResponse:
    """Pre-compiled expert doctrine."""
    topic: str
    quick_answer: str  # 2-3 sentences, instant
    full_doctrine: str  # Complete audit-defense reasoning
    case_law: List[str]  # Key citations
    irc_refs: List[str]  # IRC sections
    audit_playbook: str  # What to do under examination


# Pre-cached doctrine for common tax controversy topics
DOCTRINE_CACHE: Dict[str, DoctrineResponse] = {

    "s_corp_reasonable_compensation": DoctrineResponse(
        topic="S-Corp Reasonable Compensation",
        quick_answer="Reasonable compensation is determined by what you'd pay a non-owner for the same services. Apply the Independent Investor Test (Exacto Spring): if ROE after salary exceeds market returns, compensation is reasonable. Bifurcate labor return, capital return, and enterprise premium.",
        full_doctrine="""
## S-Corp Reasonable Compensation - Audit Defense Doctrine

### Primary Defense: Independent Investor Test
*Exacto Spring Corp. v. Commissioner*, 196 F.3d 833 (7th Cir. 1999)

Would an independent investor be satisfied with ROE after paying the shareholder's compensation?

**Calculation:**
- Net Profit After Salary ÷ Shareholder Capital = ROE
- If ROE exceeds market rates (8-15%), compensation is reasonable

### Secondary Defense: Bifurcation Framework
Separate profit sources:
1. **Labor Return**: Hours × market hourly rate
2. **Capital Return**: Investment × reasonable ROI
3. **Enterprise Premium**: Residual (systems/goodwill, not current labor)

### Burden of Proof
IRS must prove compensation is unreasonable. Demand examiner's counter-data.

### Procedural Escalation
- Request written rejection rationale
- Invoke IRM 4.10.7.2.9.8
- Request TAM if examiner persists
- Appeals Officers are more receptive to economic analysis
""",
        case_law=["Exacto Spring Corp. v. Commissioner, 196 F.3d 833 (7th Cir. 1999)",
                  "Menard Inc. v. Commissioner, 560 F.3d 620 (7th Cir. 2009)",
                  "Mulcahy, Pauritsch, Salvador & Co. v. Commissioner, T.C. Memo 2011-74"],
        irc_refs=["§1366(e)", "§3121", "§162"],
        audit_playbook="""
1. Document comparable salaries from 2-3 independent sources
2. Calculate ROE to satisfy Independent Investor Test
3. Prepare bifurcation analysis (labor/capital/enterprise)
4. Draft job description and time allocation
5. If challenged: demand examiner's alternative data
6. Escalate to Appeals if field rejects reasonable position
"""
    ),

    "capital_vs_labor_attribution": DoctrineResponse(
        topic="Capital vs Labor Profit Attribution",
        quick_answer="Counter IRS 'profits = ownership value' argument with: (1) Independent Investor Test showing adequate ROE, (2) Replacement Cost Test proving market rate, (3) Bifurcation of labor, capital, and enterprise premium, (4) Goodwill is IRC §197 capital asset, not current wages.",
        full_doctrine="""
## Countering IRS Capital vs Labor Attribution

### The IRS Position
"Profits derive from ownership, not just labor. More should be wages."

### Counter-Argument Framework

**1. Independent Investor Test**
Calculate post-salary ROE. If it exceeds market rates, an independent investor would be satisfied.

**2. Replacement Cost Test**
"What would it cost to replace me?" Document CEO/COO/CFO replacement costs. Market rates don't change based on profitability.

**3. Bifurcation Analysis**
- Labor Component: Hours × market rate
- Capital Component: Investment × reasonable ROI (8-15%)
- Enterprise Premium: Residual = systems/goodwill, not current labor

**4. Goodwill Defense**
Excess profits reflect IRC §197 intangible assets built over years. Cannot recharacterize historical capital accumulation as current wages.

**5. Burden Shifting**
IRS has burden under §1366(e). Demand their comparable data. Rejection without counter-evidence is arbitrary.

### Capital-Intensive Business Defense
If business requires substantial equipment/inventory/working capital, profits are generated by capital assets, not personal services.
""",
        case_law=["Exacto Spring Corp. v. Commissioner, 196 F.3d 833",
                  "Elliots, Inc. v. Commissioner, 716 F.2d 1241 (9th Cir. 1983)",
                  "Owensby & Kritikos, Inc. v. Commissioner, 819 F.2d 1315 (5th Cir. 1987)"],
        irc_refs=["§1366(e)", "§197", "§162", "§3121"],
        audit_playbook="""
1. Prepare ROE calculation (Independent Investor Test)
2. Document capital investment on balance sheet
3. Create bifurcation analysis spreadsheet
4. Gather replacement cost data for all owner functions
5. Identify goodwill/intangible assets on books
6. Challenge examiner to provide counter-data
"""
    ),

    "home_office_deduction": DoctrineResponse(
        topic="Home Office Deduction",
        quick_answer="Two methods: Regular (actual expenses × business %) or Simplified ($5/sq ft, max 300 sq ft = $1,500). Must meet regular and exclusive use test. Principal place of business OR place to meet clients OR separate structure.",
        full_doctrine="""
## Home Office Deduction - IRC §280A

### Qualification Tests
1. **Regular and Exclusive Use**: Space used regularly and exclusively for business
2. **Principal Place of Business**: Where you conduct substantial administrative/management activities
   - OR: Place to meet clients/customers
   - OR: Separate structure used for business

### Regular Method
Calculate percentage of home used for business:
- Square footage method: Office sq ft ÷ Total sq ft
- Room method: Rooms used ÷ Total rooms

Apply percentage to:
- Mortgage interest/rent
- Utilities
- Insurance
- Repairs
- Depreciation (home office portion)

### Simplified Method
- $5 per square foot
- Maximum 300 sq ft = $1,500
- No depreciation recapture

### Audit Defense
- Floor plan with measurements
- Photos of dedicated space
- Calendar showing regular use
- No personal items in space (exclusive use)
""",
        case_law=["Commissioner v. Soliman, 506 U.S. 168 (1993)",
                  "Popov v. Commissioner, 246 F.3d 1190 (9th Cir. 2001)"],
        irc_refs=["§280A", "§162"],
        audit_playbook="""
1. Photograph office space showing business-only use
2. Measure and document square footage
3. Keep floor plan on file
4. Maintain log of business activities performed there
5. For regular method: retain all utility/insurance/mortgage records
"""
    ),

    "percentage_depletion_oil_gas": DoctrineResponse(
        topic="Percentage Depletion - Oil & Gas",
        quick_answer="15% of gross income from property, limited to 100% of net income (65% for certain producers). Available to independent producers and royalty owners, NOT integrated oil companies. Must have economic interest in mineral deposit.",
        full_doctrine="""
## Percentage Depletion - IRC §613A

### Basic Calculation
- 15% of gross income from the property
- Limited to 100% of net income from property
- 65% of taxable income limitation for certain producers

### Eligibility
**Allowed for:**
- Independent producers (not retailers >$5M or refiners >75,000 bbl/day)
- Royalty owners
- Working interest owners

**NOT allowed for:**
- Integrated oil companies
- Retailers of oil/gas products exceeding thresholds
- Large refiners

### Production Limits
- 1,000 barrels of oil per day (or equivalent natural gas)
- Depletable quantity allocated among properties

### Economic Interest Requirement
Must have:
- Capital investment in mineral deposit
- Right to income from extraction
- Look to minerals for return of capital

### Cost Depletion Alternative
If cost depletion exceeds percentage depletion, use cost depletion instead.
""",
        case_law=["Parsons v. Smith, 359 U.S. 215 (1959)",
                  "Commissioner v. Southwest Exploration Co., 350 U.S. 308 (1956)"],
        irc_refs=["§611", "§612", "§613", "§613A", "§614"],
        audit_playbook="""
1. Document economic interest in each property
2. Track production volumes daily
3. Calculate both cost and percentage depletion
4. Verify independent producer status
5. Maintain property-by-property income records
"""
    ),

    "intangible_drilling_costs": DoctrineResponse(
        topic="Intangible Drilling Costs (IDC)",
        quick_answer="IDC can be expensed immediately (83%) or capitalized over 60 months. IDC includes: wages, fuel, supplies, ground clearing, drilling mud - anything with no salvage value. Tangible costs (casing, tubing, equipment) must be capitalized and depreciated.",
        full_doctrine="""
## Intangible Drilling Costs - IRC §263(c)

### Definition
Costs incurred in drilling that have no salvage value:
- Wages, fuel, repairs, hauling, supplies
- Ground clearing and draining
- Road making
- Drilling mud and chemicals
- Core analysis
- Formation testing

### Election Options
1. **Expense Immediately**: Deduct in year incurred (most common)
2. **Capitalize**: Amortize over 60 months
3. **Optional Capitalization**: Add to basis for depletion

### NOT IDC (Must Capitalize)
- Casing, tubing, wellhead equipment
- Storage tanks
- Pipelines
- Anything with salvage value

### AMT Preference
IDC is an AMT preference item under §57(a)(2):
- Excess IDC over 10-year amortization is preference
- May trigger AMT liability

### At-Risk Rules
IDC deductions limited to amount at risk under §465.

### Passive Activity Rules
Working interest exception: §469(c)(3) - working interest in oil/gas is NOT passive activity if taxpayer has unlimited liability.
""",
        case_law=["Commissioner v. Binghamton Sand & Gravel, Inc., 398 F.2d 569",
                  "Brountas v. Commissioner, 73 T.C. 491 (1979)"],
        irc_refs=["§263(c)", "§57(a)(2)", "§465", "§469(c)(3)", "§59(e)"],
        audit_playbook="""
1. Segregate IDC from tangible costs on AFE
2. Document election on first return claiming IDC
3. Maintain drilling invoices with IDC/tangible breakdown
4. Calculate AMT preference if applicable
5. Document working interest for passive activity exception
"""
    ),

    "qbi_deduction_199a": DoctrineResponse(
        topic="Qualified Business Income Deduction (QBI) - §199A",
        quick_answer="20% deduction on qualified business income from pass-throughs. Above threshold ($191,950 single / $383,900 MFJ), limited by W-2 wages or W-2 + capital. SSTB income phases out entirely above thresholds. Aggregation election available.",
        full_doctrine="""
## Qualified Business Income Deduction - IRC §199A

### Basic Calculation
Lesser of:
1. 20% of QBI from each qualified trade or business, OR
2. 20% of taxable income minus net capital gains

### Income Thresholds (2024)
- Single: $191,950 (phase-out to $241,950)
- MFJ: $383,900 (phase-out to $483,900)

### Above Threshold Limitations
Greater of:
- 50% of W-2 wages, OR
- 25% of W-2 wages + 2.5% of UBIA (unadjusted basis of qualified property)

### SSTB Rules
Specified Service Trade or Business:
- Health, law, accounting, actuarial, performing arts, consulting, athletics, financial services, brokerage
- Above thresholds: QBI phases out entirely
- Exception: Engineering and architecture are NOT SSTB

### Aggregation Election
Combine businesses if:
- Same ownership (50%+ common)
- Share common control
- Operated in coordination

### REIT/PTP Component
20% of qualified REIT dividends and PTP income (not subject to W-2/UBIA limits)
""",
        case_law=["Reg. §1.199A-1 through §1.199A-6"],
        irc_refs=["§199A", "§199A(d)", "§199A(b)(2)"],
        audit_playbook="""
1. Calculate QBI for each business separately
2. Determine if above threshold (check W-2/UBIA limits)
3. Identify any SSTB income
4. Consider aggregation election if multiple businesses
5. Document reasonable compensation for S-Corps
"""
    ),

    "child_tax_credit": DoctrineResponse(
        topic="Child Tax Credit",
        quick_answer="$2,000 per qualifying child under 17. Up to $1,700 refundable (Additional CTC). Phase-out begins at $200,000 single / $400,000 MFJ. Child must have valid SSN, be claimed as dependent, and live with taxpayer more than half the year.",
        full_doctrine="""
## Child Tax Credit - IRC §24

### Credit Amount (2024)
- $2,000 per qualifying child
- $1,700 maximum refundable portion (ACTC)
- $500 credit for other dependents (non-refundable)

### Qualifying Child Requirements
1. Age: Under 17 at end of tax year
2. Relationship: Child, stepchild, foster child, sibling, or descendant
3. Support: Child did not provide more than half own support
4. Dependent: Claimed as dependent on return
5. Residency: Lived with taxpayer more than half the year
6. Citizenship: U.S. citizen, national, or resident alien
7. SSN: Valid Social Security Number (required for CTC, not $500 credit)

### Income Phase-Out
- Single/HoH: Begins at $200,000 MAGI
- MFJ: Begins at $400,000 MAGI
- Rate: $50 reduction per $1,000 over threshold

### Additional Child Tax Credit (Refundable)
- Up to $1,700 refundable
- Calculated on Schedule 8812
- Requires earned income over $2,500
""",
        case_law=[],
        irc_refs=["§24", "§24(d)", "§24(h)"],
        audit_playbook="""
1. Verify SSN for each child
2. Document residency (school records, medical records)
3. Confirm no other taxpayer claiming same child
4. Calculate phase-out if high income
"""
    ),

    "earned_income_credit": DoctrineResponse(
        topic="Earned Income Tax Credit (EITC)",
        quick_answer="Refundable credit for low-to-moderate income workers. Max $7,830 (3+ children, 2024). Must have earned income, investment income under $11,600, valid SSN. Cannot use MFS. Qualifying child or be 25-65 with no children.",
        full_doctrine="""
## Earned Income Tax Credit - IRC §32

### Maximum Credits (2024)
| Children | Max Credit | Max Income (Single) | Max Income (MFJ) |
|----------|-----------|--------------------|--------------------|
| 0 | $632 | $18,591 | $25,511 |
| 1 | $4,213 | $49,084 | $56,004 |
| 2 | $6,960 | $55,768 | $62,688 |
| 3+ | $7,830 | $59,899 | $66,819 |

### Eligibility Requirements
1. Earned income (wages, self-employment, tips)
2. Investment income under $11,600
3. Valid SSN for taxpayer, spouse, qualifying children
4. Cannot file MFS
5. Cannot be qualifying child of another person
6. U.S. citizen or resident alien all year

### No Qualifying Child Rules
- Age 25-65 (or 18-65 for former foster youth/homeless)
- Cannot be dependent of another
- Live in U.S. more than half year

### Qualifying Child
- Age under 19 (24 if student), any age if disabled
- Relationship: child, sibling, or descendant
- Residency: U.S. residence with taxpayer over half year
- Cannot file joint return (except to claim refund)
""",
        case_law=[],
        irc_refs=["§32", "§32(c)", "§32(d)"],
        audit_playbook="""
1. Document earned income (W-2, Schedule C)
2. Verify SSNs for all claimed individuals
3. Prove residency with school/medical records
4. Track investment income to stay under limit
5. Keep records 3 years (7 if fraud suspected)
"""
    ),

    # ==================== ADDITIONAL AUDIT ISSUES ====================

    "hobby_loss_183": DoctrineResponse(
        topic="Hobby Loss Rules - §183",
        quick_answer="Activity presumed business if profitable 3 of 5 years (2 of 7 for horses). Nine factors test: profit motive, expertise, time/effort, asset appreciation, success history, income history, occasional profits, financial status, personal pleasure. Burden shifts to IRS after presumption met.",
        full_doctrine="""
## Hobby Loss - IRC §183

### The Presumption
- Profitable 3 of last 5 years = presumed business
- Horse breeding/racing: 2 of 7 years
- Burden shifts to IRS to prove no profit motive

### Nine Factors Test (Reg. §1.183-2)
1. **Manner of activity**: Businesslike books, records, methods
2. **Expertise**: Knowledge of taxpayer/advisors
3. **Time and effort**: Personal involvement
4. **Asset appreciation**: Expectation of value increase
5. **Success in similar activities**: Track record
6. **Income/loss history**: Pattern of losses vs profits
7. **Occasional profits**: Amount relative to investment
8. **Financial status**: Other income sources
9. **Personal pleasure**: Recreation elements

### No Single Factor Controls
Courts weigh all factors. Document business intent.

### If Classified as Hobby
- Income reportable
- Expenses limited to income (no loss)
- Post-TCJA: No itemized deduction for hobby expenses

### Audit Defense Strategy
- Maintain separate books/accounts
- Create business plan
- Document profit-seeking changes
- Show expertise or seek expert advice
- Track time spent on activity
""",
        case_law=["Dreicer v. Commissioner, 78 T.C. 642 (1982)",
                  "Brannen v. Commissioner, 722 F.2d 695 (11th Cir. 1984)",
                  "Nickerson v. Commissioner, 700 F.2d 402 (7th Cir. 1983)"],
        irc_refs=["§183", "§183(d)", "Reg. §1.183-2"],
        audit_playbook="""
1. Maintain contemporaneous business records
2. Create formal business plan with profit projections
3. Document all changes made to improve profitability
4. Keep time logs showing business activity
5. Separate business and personal bank accounts
6. File §183(e) election to delay determination
7. Show comparable successful businesses
"""
    ),

    "worker_classification": DoctrineResponse(
        topic="Employee vs Independent Contractor",
        quick_answer="IRS uses behavioral control, financial control, and relationship type. Key: who controls how work is done? 1099 vs W-2 affects payroll taxes, benefits, liability. Misclassification triggers back taxes + penalties. Form SS-8 for IRS determination.",
        full_doctrine="""
## Worker Classification - Employee vs Contractor

### Three-Factor Test (IRS)

**1. Behavioral Control**
- Instructions: When, where, how to work
- Training: Employee = trained; Contractor = brings expertise
- Integration: Part of regular operations?

**2. Financial Control**
- Investment: Contractor has own tools/equipment
- Expenses: Contractor has unreimbursed costs
- Profit/Loss opportunity: Contractor can profit or lose
- Multiple clients: Contractor serves multiple customers
- Payment method: Contractor paid by job, not hour

**3. Type of Relationship**
- Written contracts: Terms of engagement
- Benefits: Employees get benefits; contractors don't
- Permanency: Ongoing = employee; project = contractor
- Key services: Core business function = likely employee

### Consequences of Misclassification
- Back employment taxes (employer + employee share)
- Interest and penalties
- Potential Section 530 relief (good faith)
- State law consequences (unemployment, workers comp)

### Safe Harbor - Section 530
Relief if:
- Reasonable basis for treatment
- Consistent treatment of similar workers
- Filed all 1099s
""",
        case_law=["Nationwide Mutual Insurance Co. v. Darden, 503 U.S. 318 (1992)",
                  "Rev. Rul. 87-41 (20-factor test)",
                  "Vizcaino v. Microsoft Corp., 120 F.3d 1006 (9th Cir. 1997)"],
        irc_refs=["§3401", "§3121", "§530 of Revenue Act of 1978"],
        audit_playbook="""
1. Document independent contractor agreements in writing
2. Ensure contractors have own business entity/insurance
3. Avoid behavioral control (don't dictate hours, methods)
4. Pay by project, not hourly
5. File Form SS-8 if uncertain (before IRS audit)
6. Assert Section 530 relief if audited
7. Keep 1099s and contractor invoices
"""
    ),

    "charitable_contributions": DoctrineResponse(
        topic="Charitable Contribution Audits",
        quick_answer="Cash: bank record or receipt. $250+: contemporaneous written acknowledgment. Non-cash >$500: Form 8283. >$5,000: qualified appraisal required. Vehicle/art/real estate have special rules. Overvaluation penalty: 20-40% of underpayment.",
        full_doctrine="""
## Charitable Contributions - Audit Defense

### Documentation Requirements by Amount

**Under $250**
- Bank record, receipt, or written communication from charity
- Shows: organization name, date, amount

**$250 and Over**
- Contemporaneous written acknowledgment from charity
- Must state: amount, goods/services provided, good faith estimate of value
- Must obtain BEFORE filing return

**Non-Cash Over $500**
- Form 8283 required
- Description of property, date acquired, basis, FMV

**Non-Cash Over $5,000**
- Qualified appraisal by qualified appraiser
- Appraisal summary on Form 8283 signed by appraiser and donee
- Exception: publicly traded securities

### Special Property Rules

**Vehicles, Boats, Aircraft**
- If charity sells within 3 years: deduction = sale price
- Form 1098-C from charity required

**Art/Collectibles**
- Over $20,000: attach complete appraisal to return
- IRS Art Advisory Panel may review

**Real Estate**
- Qualified appraisal required
- Conservation easements: enhanced scrutiny

### Valuation Penalties
- 20% penalty if overvalued by 150%+
- 40% penalty if overvalued by 200%+ (gross misstatement)
""",
        case_law=["Hewitt v. Commissioner, 109 T.C. 258 (1997)",
                  "RERI Holdings I, LLC v. Commissioner, 149 T.C. 1 (2017)",
                  "Alli v. Commissioner, T.C. Memo 2014-15"],
        irc_refs=["§170", "§170(f)(8)", "§170(f)(11)", "§6662"],
        audit_playbook="""
1. Obtain acknowledgment letter BEFORE filing
2. For non-cash: photograph items, keep purchase records
3. Use qualified appraisers for items over $5,000
4. Complete Form 8283 accurately
5. Retain all supporting documentation 7 years
6. For conservation easements: expect heavy scrutiny
"""
    ),

    "travel_entertainment": DoctrineResponse(
        topic="Travel & Entertainment Deductions",
        quick_answer="Must be ordinary, necessary, and have business purpose. Travel: away from tax home overnight. Meals: 50% deductible, must document business discussion. Entertainment: NOT deductible post-TCJA. Substantiation: amount, date, place, business purpose, relationship.",
        full_doctrine="""
## Travel & Entertainment - IRC §274

### Travel Expenses (Away from Home)
Deductible if:
- Away from tax home overnight
- Primary purpose is business

**Deductible:**
- Transportation (air, rail, car)
- Lodging
- 50% of meals (100% if employer-provided for convenience)
- Dry cleaning, tips, internet

**Tax Home**
- Principal place of business
- If no regular workplace: where you regularly live
- If itinerant: nowhere is tax home

### Meals (50% Deductible)
Requirements:
- Not lavish or extravagant
- Taxpayer or employee present
- Business discussion before, during, or after

**100% Deductible Exceptions:**
- Company-wide events
- Meals as taxable compensation
- De minimis fringe benefits

### Entertainment (POST-TCJA)
- **NO DEDUCTION** for entertainment, amusement, recreation
- Includes: sporting events, golf, theater, clubs
- Exception: Compensation to employees is deductible

### Substantiation (Cohan Rule Limited)
Must document:
1. Amount of expense
2. Date and place
3. Business purpose
4. Business relationship of persons

**No reconstruction allowed for travel/entertainment.**
""",
        case_law=["Cohan v. Commissioner, 39 F.2d 540 (2d Cir. 1930)",
                  "Sanford v. Commissioner, 50 T.C. 823 (1968)",
                  "Sutter v. Commissioner, 21 T.C. 170 (1953)"],
        irc_refs=["§162", "§274", "§274(d)", "§274(n)"],
        audit_playbook="""
1. Keep contemporaneous expense log
2. Retain all receipts (credit card statements insufficient alone)
3. Document business purpose on receipt
4. Note attendees and business relationship
5. Separate meals from entertainment on receipts
6. Use expense tracking app with photo capture
"""
    ),

    "vehicle_mileage": DoctrineResponse(
        topic="Vehicle & Mileage Deductions",
        quick_answer="Standard mileage 2024: 67¢/mile. OR actual expenses (gas, insurance, depreciation). Must keep contemporaneous mileage log. Personal use not deductible. Commuting is personal. Listed property rules apply. Luxury auto limits on depreciation.",
        full_doctrine="""
## Vehicle Deductions - IRC §274(d), §280F

### Two Methods

**1. Standard Mileage Rate**
- 2024: 67 cents per mile
- Plus: parking, tolls (business portion)
- Cannot use if: fleet of 5+, claimed depreciation, §179, bonus

**2. Actual Expense Method**
- Gas, oil, repairs, insurance, registration
- Depreciation (subject to luxury limits)
- Lease payments (inclusion amount may apply)
- Multiply by business use percentage

### Mileage Log Requirements
Must document:
- Date of trip
- Destination and business purpose
- Miles driven
- Total miles for year (business + personal)

**Contemporaneous = at or near time of trip**

### Commuting
- Home to regular work location = NOT deductible
- Home to temporary location = deductible
- Between two work locations = deductible

### Listed Property (§280F)
- Vehicle is listed property
- If business use <50%: straight-line depreciation only
- Must substantiate business use

### Luxury Auto Limits (2024)
- Year 1: $12,200 ($20,200 with bonus)
- Year 2: $19,500
- Year 3: $11,700
- Year 4+: $6,960
""",
        case_law=["Temp. Reg. §1.274-5T",
                  "Bogue v. Commissioner, T.C. Memo 2011-164"],
        irc_refs=["§274(d)", "§280F", "§179", "§168(k)"],
        audit_playbook="""
1. Maintain contemporaneous mileage log (app or paper)
2. Record odometer at start and end of year
3. Document business purpose for each trip
4. Calculate business use percentage annually
5. If actual method: keep all receipts
6. For mixed-use: allocate between business/personal
"""
    ),

    "passive_activity_losses": DoctrineResponse(
        topic="Passive Activity Loss Rules - §469",
        quick_answer="Passive losses only offset passive income. Material participation: 500+ hours, substantially all, 100+ hours if no one else more. Rental is per se passive (exceptions: real estate professional, short-term). Suspended losses released on disposition.",
        full_doctrine="""
## Passive Activity Losses - IRC §469

### General Rule
- Passive losses cannot offset active/portfolio income
- Suspended losses carry forward
- Released on complete taxable disposition

### Material Participation Tests (Any One)
1. 500+ hours participation during year
2. Substantially all participation (you vs others)
3. 100+ hours AND no one else more
4. Significant participation activity: 100+ hours, aggregate 500+ across all SPAs
5. Materially participated 5 of last 10 years
6. Personal service activity: any 3 prior years
7. Facts and circumstances (rarely used)

### Rental Activities
- Per se passive (regardless of hours)
- Exception: Real Estate Professional status

**Real Estate Professional:**
- 750+ hours in real property trades/businesses
- More than half of personal services in real property
- Then: material participation test for each property

### Special Rules
- **Working Interest Exception**: Oil/gas working interest with unlimited liability = not passive
- **$25,000 Rental Allowance**: Active participation, phases out $100K-$150K AGI
- **Grouping Election**: Combine activities if appropriate economic unit

### Disposition
- Complete disposition releases suspended losses
- Installment sale: losses released pro-rata
- Gift: losses attach to basis
- Death: losses lost (step-up basis)
""",
        case_law=["Temp. Reg. §1.469-5T",
                  "Assaf v. Commissioner, T.C. Memo 2005-14",
                  "Beecher v. Commissioner, T.C. Memo 2010-145"],
        irc_refs=["§469", "§469(c)(7)", "§469(i)"],
        audit_playbook="""
1. Maintain detailed time logs for each activity
2. Document nature of participation (not just hours)
3. Consider grouping election if multiple activities
4. For real estate: track 750-hour requirement
5. Calculate suspended losses annually
6. On disposition: release carryover losses
"""
    ),

    "like_kind_exchange_1031": DoctrineResponse(
        topic="Like-Kind Exchange - §1031",
        quick_answer="Defer gain by exchanging real property for real property. Post-2017: only real estate qualifies. 45-day ID period, 180-day exchange period. Boot is taxable. Qualified intermediary required. Related party rules apply.",
        full_doctrine="""
## Like-Kind Exchange - IRC §1031

### Basic Requirements (Post-TCJA)
- Only REAL PROPERTY qualifies (no personal property)
- Both relinquished and replacement must be real property
- Held for productive use in trade/business or investment
- NOT: inventory, stock, partnership interests, primary residence

### Timeline (Strict)
- **Day 0**: Close on relinquished property
- **Day 45**: Identify replacement property (in writing)
- **Day 180**: Close on replacement property

### Identification Rules
Choose one:
- 3-Property Rule: Up to 3 properties, any value
- 200% Rule: Any number, FMV ≤ 200% of relinquished
- 95% Rule: Any number if 95% acquired

### Boot = Taxable
- Cash received = taxable
- Net mortgage relief = taxable
- Unlike property received = taxable

### Qualified Intermediary (QI)
- Required for deferred exchanges
- Cannot be related party or agent
- Holds funds between transactions

### Related Parties
- Exchange with related party: 2-year holding required
- Early disposition = recognition of deferred gain
- Related = family, >50% owned entities
""",
        case_law=["Starker v. United States, 602 F.2d 1341 (9th Cir. 1979)",
                  "Reg. §1.1031(a)-1 through (k)-1"],
        irc_refs=["§1031", "§1031(a)(3)", "§1031(f)"],
        audit_playbook="""
1. Use qualified intermediary (never touch funds)
2. Document 45-day identification in writing
3. Match or exceed debt to avoid boot
4. Verify both properties are real estate
5. Keep closing statements for basis tracking
6. Related party: hold replacement 2+ years
"""
    ),

    "unreported_income_cash": DoctrineResponse(
        topic="Unreported Income - Cash Business Audit",
        quick_answer="IRS uses indirect methods: bank deposits, net worth, cash T analysis. Burden shifts to taxpayer to explain deposits. Specific item method preferred. Badges of fraud trigger 75% penalty + criminal referral. Voluntary disclosure program available.",
        full_doctrine="""
## Unreported Income - Cash Business Audits

### IRS Indirect Methods

**1. Bank Deposits Method**
- Total deposits - known non-income items = income
- Taxpayer must explain every deposit
- Burden to prove deposits aren't income

**2. Net Worth Method**
- Ending net worth - beginning net worth + living expenses = income
- Requires establishing accurate opening net worth
- Best for lifestyle audits

**3. Cash T Analysis**
- Cash available + income = cash spent + ending cash
- Discrepancies = unreported income
- Used for specific years

**4. Markup Method**
- Compare gross profit to industry standards
- Inventory analysis
- Cost of goods sold verification

### Statute of Limitations
- Standard: 3 years from filing
- 25%+ omission: 6 years
- Fraud: No limit
- Non-filing: No limit

### Badges of Fraud
- Understatement of income
- Two sets of books
- False entries, invoices, documents
- Destruction of records
- Concealment of assets
- Failure to cooperate
- Implausible explanations

### Penalties
- Accuracy: 20% (negligence/substantial understatement)
- Fraud: 75% (civil)
- Criminal: Fines + imprisonment
""",
        case_law=["Holland v. United States, 348 U.S. 121 (1954)",
                  "United States v. Massei, 355 U.S. 595 (1958)"],
        irc_refs=["§61", "§446", "§6501", "§6663", "§7201"],
        audit_playbook="""
1. Reconstruct all bank deposits immediately
2. Identify non-income sources (loans, gifts, transfers)
3. Gather loan documents, gift letters, inheritance records
4. Analyze lifestyle vs reported income
5. If fraud suspected: invoke 5th Amendment, get counsel
6. Consider voluntary disclosure if willful
7. Challenge IRS reconstruction methodology
"""
    ),

    "cryptocurrency_audit": DoctrineResponse(
        topic="Cryptocurrency Tax Issues",
        quick_answer="Crypto is property, not currency. Every sale/exchange/use is taxable event. Cost basis tracking critical. Mining = ordinary income at FMV. Staking rewards = income. Form 8949 required. IRS has Coinbase/exchange data via John Doe summons.",
        full_doctrine="""
## Cryptocurrency Taxation

### Basic Tax Treatment
- Cryptocurrency = property (Notice 2014-21)
- NOT currency for tax purposes
- Capital gains rules apply

### Taxable Events
- Sell crypto for fiat
- Exchange crypto for crypto
- Use crypto to buy goods/services
- Receive crypto as payment
- Mining rewards
- Staking rewards
- Airdrops
- Hard forks (when you have dominion)

### NOT Taxable
- Buy crypto with fiat (acquire only)
- Transfer between own wallets
- Gift crypto (but gift tax may apply)

### Basis Tracking
- Specific identification preferred
- FIFO if not specified
- Include exchange fees in basis

### Income Types
- **Short-term capital gain**: Held ≤ 1 year (ordinary rates)
- **Long-term capital gain**: Held > 1 year (0/15/20%)
- **Mining income**: Ordinary income at FMV when received
- **Staking rewards**: Ordinary income

### Reporting
- Form 8949 for each transaction
- Schedule D summary
- Form 1040 checkbox: "Did you receive, sell, exchange..."

### IRS Enforcement
- John Doe summons to exchanges (Coinbase, Kraken)
- Form 1099 matching
- Voluntary disclosure for past non-compliance
""",
        case_law=["Notice 2014-21", "Rev. Rul. 2019-24", "IRS FAQs on Virtual Currency"],
        irc_refs=["§1001", "§1012", "§61"],
        audit_playbook="""
1. Reconstruct complete transaction history
2. Use crypto tax software (CoinTracker, Koinly)
3. Document cost basis for every acquisition
4. Match exchange 1099s to reported gains
5. Report all income (mining, staking, airdrops)
6. If prior non-compliance: consider amended returns
"""
    ),

    "fbar_fatca_foreign": DoctrineResponse(
        topic="Foreign Accounts - FBAR & FATCA",
        quick_answer="FBAR (FinCEN 114): $10K aggregate foreign accounts, file by April 15 (auto extension Oct 15). FATCA (Form 8938): higher thresholds ($50K-$600K based on filing status/residence). Willful penalty: greater of $100K or 50% of account. Non-willful: up to $10K per violation.",
        full_doctrine="""
## Foreign Account Reporting

### FBAR - FinCEN Form 114
**Who Files:**
- U.S. persons (citizens, residents, entities)
- Aggregate foreign accounts > $10,000 at any time during year

**What's Reported:**
- Bank accounts, securities accounts
- Signature authority accounts
- Accounts where you have financial interest

**Deadline:**
- April 15 (automatic extension to October 15)
- Filed electronically through BSA E-Filing

### FATCA - Form 8938
**Thresholds (Unmarried, Living in US):**
- End of year: $50,000
- Any time during year: $75,000

**Thresholds (Married Filing Jointly, US):**
- End of year: $100,000
- Any time: $150,000

**Living Abroad: Double the thresholds**

**What's Reported:**
- Foreign financial accounts
- Foreign stocks, securities held outside US account
- Foreign partnership/corporation interests
- Foreign trusts, estates

### Penalties

**FBAR:**
- Non-willful: Up to $10,000 per violation
- Willful: Greater of $100,000 or 50% of account balance
- Criminal: Up to $500,000 + 10 years

**FATCA (Form 8938):**
- $10,000 failure to file
- Additional $10,000 for each 30 days (max $50,000)
- 40% understatement penalty on omitted income

### Voluntary Disclosure
- Streamlined Filing Compliance (non-willful)
- Voluntary Disclosure Practice (willful)
- Delinquent FBAR/international procedures
""",
        case_law=["United States v. Williams, 489 Fed. Appx. 655 (4th Cir. 2012)",
                  "Bedrosian v. United States, 912 F.3d 144 (3d Cir. 2018)"],
        irc_refs=["31 USC §5314 (FBAR)", "§6038D (FATCA)", "§6662(j)"],
        audit_playbook="""
1. Determine all foreign accounts/assets
2. Calculate aggregate balance for FBAR threshold
3. File delinquent FBARs if non-willful
4. Consider streamlined procedures if eligible
5. Report income from foreign accounts
6. Maintain records of foreign account statements
"""
    ),

    "estimated_tax_penalty": DoctrineResponse(
        topic="Estimated Tax Penalty - §6654",
        quick_answer="Penalty for underpaying quarterly estimates. Safe harbor: pay 100% of prior year tax (110% if AGI >$150K) OR 90% of current year. Annualized income method for uneven income. Penalty = interest on underpayment. Form 2210 to calculate or request waiver.",
        full_doctrine="""
## Estimated Tax Penalty - IRC §6654

### Who Must Pay Estimates
- Expect to owe $1,000+ after withholding
- Self-employed, investors, rental income
- Quarterly: April 15, June 15, Sept 15, Jan 15

### Safe Harbor (Avoid Penalty)
Pay at least:
- 90% of current year tax, OR
- 100% of prior year tax (110% if prior year AGI > $150,000)

### Penalty Calculation
- Interest rate on underpayment
- Calculated by quarter
- From due date to payment date

### Annualized Income Method
- For uneven income (e.g., seasonal business)
- Calculate tax based on income through each quarter
- Form 2210 Schedule AI

### Penalty Exceptions
- Tax owed < $1,000
- Withholding covers 100%/110% of prior year
- Prior year was full 12-month year
- Prior year had no tax liability

### Waiver for Unusual Circumstances
- Casualty, disaster, unusual circumstance
- Retirement (age 62+) in year or prior year
- Request on Form 2210

### Farmers and Fishermen
- Only one payment due: January 15
- Pay 66.67% of current year OR 100% of prior
""",
        case_law=["Reg. §1.6654-1"],
        irc_refs=["§6654", "§6654(d)(1)(B)", "§6654(e)"],
        audit_playbook="""
1. Calculate safe harbor amount at year start
2. Increase withholding from W-2 if possible
3. Make quarterly payments on time
4. If uneven income: use annualized method
5. Request waiver if unusual circumstances
"""
    ),

    "statute_of_limitations": DoctrineResponse(
        topic="Statute of Limitations - Assessment & Collection",
        quick_answer="Assessment: 3 years from filing (later of due date or actual filing). 6 years if 25%+ omission. No limit for fraud or non-filing. Collection: 10 years from assessment. Tolled by: bankruptcy, OIC, CDP, taxpayer abroad, military.",
        full_doctrine="""
## Statute of Limitations

### Assessment Period (IRS Can Audit)

**3-Year Rule (General)**
- Runs from later of: filing date or due date
- Early filing = runs from due date

**6-Year Rule**
- Omit 25%+ of gross income
- Overstate basis by 25%+
- Foreign financial asset understatement

**No Limit**
- Fraud with intent to evade
- Willful failure to file
- False or fraudulent return

### Collection Period
**10 Years from Assessment**
- Runs from date of assessment
- Can be extended by agreement

**Tolling Events (Clock Stops):**
- Bankruptcy (+ 6 months after)
- Offer in Compromise (pending + 30 days)
- CDP hearing (pending + 30 days)
- Taxpayer abroad 6+ months
- Military combat zone
- Lawsuit to collect

### Refund Claims
**3 Years from Filing OR 2 Years from Payment**
- Whichever is later
- If claim within 3 years of filing: refund limited to tax paid in prior 3 years + extensions

### Protective Claim
- File within statute to preserve right
- Allows amendment after statute if contingencies resolve
""",
        case_law=["Colony, Inc. v. Commissioner, 357 U.S. 28 (1958)",
                  "United States v. Home Concrete & Supply, LLC, 566 U.S. 478 (2012)"],
        irc_refs=["§6501", "§6502", "§6511", "§6531"],
        audit_playbook="""
1. Calculate ASED (Assessment Statute Expiration Date)
2. Never extend without cause
3. Monitor CSED for collection
4. File protective claims before refund statute expires
5. If fraud alleged: seek representation immediately
"""
    ),

    "offer_in_compromise": DoctrineResponse(
        topic="Offer in Compromise (OIC)",
        quick_answer="Settle tax debt for less than owed. Three grounds: doubt as to collectability (most common), doubt as to liability, effective tax administration. RCP = monthly income × 12 or 24 + asset equity. 20% deposit required with Form 656. IRS has 24 months to decide.",
        full_doctrine="""
## Offer in Compromise - IRC §7122

### Three Grounds for OIC

**1. Doubt as to Collectability (DATC)**
- Most common basis
- Can't pay full amount in reasonable time
- RCP (Reasonable Collection Potential) < liability

**2. Doubt as to Liability (DATL)**
- Genuine dispute about amount owed
- Separate Form 656-L

**3. Effective Tax Administration (ETA)**
- Can pay but creates economic hardship
- Public policy or equity considerations
- Rare, high burden

### Reasonable Collection Potential (RCP)
**Formula:**
- Asset equity (quick sale value - encumbrances)
- PLUS: Future income
  - Lump sum: Monthly income × 12
  - Periodic: Monthly income × 24

### Process
1. Confirm eligibility (filed all returns, current on estimates)
2. Complete Form 433-A (OIC) or 433-B (OIC) for businesses
3. Complete Form 656
4. Pay $205 application fee (waiver if low income)
5. Pay 20% of offer (lump sum) or first month payment (periodic)

### Timeline
- IRS has 24 months to decide
- If no decision: offer deemed accepted
- Collection suspended during consideration

### After Acceptance
- 5-year compliance period
- File and pay all taxes timely
- Breach = reinstatement of full liability
""",
        case_law=["Reg. §301.7122-1", "IRM 5.8 (Offer in Compromise)"],
        irc_refs=["§7122", "§7122(c)", "§7122(d)"],
        audit_playbook="""
1. Verify all returns filed before applying
2. Get current on estimated tax payments
3. Complete financial disclosure accurately
4. Calculate RCP before submitting
5. Consider lump sum vs periodic payment
6. If rejected: request Appeals review
7. Maintain compliance during 5-year period
"""
    ),

    "innocent_spouse_relief": DoctrineResponse(
        topic="Innocent Spouse Relief - §6015",
        quick_answer="Relief from joint return liability caused by spouse/ex-spouse. Three types: Traditional (§6015(b)), Separation of Liability (§6015(c)), Equitable Relief (§6015(f)). Must request within 2 years of collection activity (10 years for equitable). Form 8857.",
        full_doctrine="""
## Innocent Spouse Relief - IRC §6015

### Traditional Innocent Spouse (§6015(b))
**Requirements:**
1. Joint return filed
2. Understatement due to erroneous item of spouse
3. Didn't know and had no reason to know
4. Inequitable to hold liable

### Separation of Liability (§6015(c))
**Requirements:**
1. Joint return filed
2. No longer married OR legally separated OR lived apart 12+ months
3. Allocate liability between spouses
4. If knew of understatement: no relief for that portion

### Equitable Relief (§6015(f))
**When Traditional/Separation Don't Apply:**
- Understated tax OR underpayment
- Considering all facts and circumstances, inequitable

**Factors Considered:**
- Marital status
- Economic hardship
- Knowledge or reason to know
- Legal obligation (divorce decree)
- Significant benefit from understatement
- Compliance history
- Mental/physical health

### Deadline
- Traditional/Separation: 2 years from first collection activity
- Equitable: No later than CSED (10 years)

### Process
- File Form 8857
- IRS must contact other spouse (unless exception)
- Can request informal conference or Appeals
""",
        case_law=["Rev. Proc. 2013-34 (equitable relief factors)",
                  "Cheshire v. Commissioner, 282 F.3d 326 (5th Cir. 2002)"],
        irc_refs=["§6015", "§6015(b)", "§6015(c)", "§6015(f)"],
        audit_playbook="""
1. File Form 8857 before deadline
2. Document lack of knowledge (separate finances, etc.)
3. Show no significant benefit from understatement
4. Demonstrate economic hardship if applicable
5. If denied: request Appeals
6. Consider Tax Court petition
"""
    ),

    "trust_fund_recovery_penalty": DoctrineResponse(
        topic="Trust Fund Recovery Penalty - §6672",
        quick_answer="100% penalty for failing to pay withheld payroll taxes. Applies to 'responsible persons' who willfully fail to pay. Includes: owners, officers, directors, bookkeepers with check-signing authority. Joint and several liability. Form 4180 interview determines responsibility.",
        full_doctrine="""
## Trust Fund Recovery Penalty - IRC §6672

### What It Covers
- Federal income tax withheld from employees
- Employee share of FICA (Social Security, Medicare)
- NOT: Employer share of FICA, FUTA

### Two Requirements
**1. Responsible Person**
- Authority to decide which creditors to pay
- Control over finances
- Includes: owners, officers, directors, controlling shareholders
- May include: bookkeeper, CFO, controller

**2. Willfulness**
- Knowledge taxes due
- Paid other creditors instead
- Does NOT require evil intent

### Multiple Responsible Persons
- IRS can assess against all
- Joint and several liability
- Contribution rights among responsible parties

### Assessment Process
1. IRS conducts Form 4180 interview
2. Determines responsible persons
3. Letter 1153 proposes assessment
4. 60 days to protest (Letter 1153)
5. Appeals conference
6. Assessment if no protest or after Appeals

### Defense Strategies
- Not a responsible person (no financial authority)
- Not willful (reasonable cause, no knowledge)
- Already collected from another responsible person
- Designate payments to trust fund (but see voluntary rules)
""",
        case_law=["Slodov v. United States, 436 U.S. 238 (1978)",
                  "Gephart v. United States, 818 F.2d 469 (6th Cir. 1987)"],
        irc_refs=["§6672", "§7501"],
        audit_playbook="""
1. Don't give Form 4180 interview without representation
2. Document who had financial control
3. Show you were not authorized to sign checks
4. If responsible: prove reasonable cause
5. Consider contribution claims against other responsible parties
6. Flora full payment: Sue for refund in district court
"""
    ),

    "depreciation_cost_segregation": DoctrineResponse(
        topic="Depreciation & Cost Segregation",
        quick_answer="Buildings: 27.5 years (residential) or 39 years (commercial). Cost segregation reclassifies components to 5/7/15-year property for accelerated depreciation. Bonus depreciation: 60% in 2024, phasing down. §179 max $1.22M. Lookback studies for prior years available.",
        full_doctrine="""
## Depreciation - IRC §167, §168, §179

### MACRS Recovery Periods
| Property | Years | Method |
|----------|-------|--------|
| Equipment, vehicles | 5 | 200% DB |
| Office furniture | 7 | 200% DB |
| Land improvements | 15 | 150% DB |
| Residential rental | 27.5 | Straight-line |
| Nonresidential real | 39 | Straight-line |

### Section 179 Expensing (2024)
- Maximum deduction: $1,220,000
- Phase-out threshold: $3,050,000
- Must have taxable income to use
- Applies to tangible personal property, some software, QIP

### Bonus Depreciation (§168(k))
- 2024: 60% (phasing down 20% per year)
- New AND used property
- No taxable income requirement
- Cannot create/increase NOL for §179 (but bonus can)

### Cost Segregation
**What It Does:**
- Engineering study of building components
- Reclassifies building elements to shorter lives:
  - Electrical (5-7 year)
  - Plumbing (5-7 year)
  - Site improvements (15 year)
  - Specialized systems (5-7 year)

**Benefits:**
- Accelerated deductions
- Improved cash flow
- Bonus depreciation on reclassified components

**Lookback Studies:**
- For properties placed in service in prior years
- File Form 3115 (automatic change)
- Claim §481(a) adjustment
""",
        case_law=["Hospital Corp. of America v. Commissioner, 109 T.C. 21 (1997)"],
        irc_refs=["§167", "§168", "§179", "§168(k)", "§1250"],
        audit_playbook="""
1. Get engineering-based cost segregation study
2. Document bonus depreciation elections
3. Track §179 limitations by entity
4. Consider lookback studies for prior acquisitions
5. Maintain depreciation schedules for all assets
"""
    ),

    "rental_real_estate_losses": DoctrineResponse(
        topic="Rental Real Estate Losses",
        quick_answer="Rental is passive per se. $25K special allowance for active participation (phases out $100K-$150K AGI). Real estate professional: 750+ hours in real property trades/businesses, more than half of personal services. Must materially participate in each property (or group).",
        full_doctrine="""
## Rental Real Estate - §469

### Default Rule
- Rental activity is PASSIVE (regardless of hours)
- Losses only offset passive income
- Suspended losses carry forward

### $25,000 Special Allowance
**Requirements:**
- Active participation (less than material)
- Own 10%+ of rental
- Not a limited partner

**Phase-out:**
- Begins at $100,000 MAGI
- Completely gone at $150,000 MAGI
- $0.50 reduction per $1 over $100K

### Real Estate Professional Exception
**Requirements:**
1. 750+ hours in real property trades/businesses
2. More than half of personal services in real property
3. Then: rental NOT automatically passive

**Still Need Material Participation:**
- 500+ hours per property, OR
- Grouping election to treat as single activity

**What Counts Toward 750 Hours:**
- Real estate development
- Construction
- Property management
- Brokerage
- Rental activity itself

### Short-Term Rentals
- Average customer use 7 days or less: NOT rental activity
- Average use 30 days or less WITH significant services: NOT rental activity
- Apply material participation directly
""",
        case_law=["Reg. §1.469-9",
                  "Toups v. Commissioner, T.C. Memo 2018-99"],
        irc_refs=["§469", "§469(c)(7)", "§469(i)"],
        audit_playbook="""
1. Maintain detailed time logs (date, hours, activity)
2. Document active vs material participation level
3. Track 750-hour requirement for RE professional
4. Consider grouping election for multiple properties
5. Calculate AGI for $25K allowance phase-out
6. Keep records of all rental income and expenses
"""
    ),
}


class TaxDoctrineEngine:
    """Fast doctrine lookup with RAG fallback."""

    def __init__(self):
        self.cache = DOCTRINE_CACHE
        self._build_keyword_index()

    def _build_keyword_index(self):
        """Build keyword-to-topic mapping for fast lookup."""
        self.keyword_index: Dict[str, List[str]] = {}

        keyword_map = {
            "s_corp_reasonable_compensation": [
                "s-corp", "s corp", "reasonable compensation", "salary",
                "shareholder employee", "payroll", "wages", "distribution"
            ],
            "capital_vs_labor_attribution": [
                "capital", "labor", "ownership", "profit attribution",
                "independent investor", "exacto spring", "bifurcation"
            ],
            "home_office_deduction": [
                "home office", "280a", "work from home", "office in home",
                "simplified method", "regular exclusive"
            ],
            "percentage_depletion_oil_gas": [
                "percentage depletion", "depletion", "oil", "gas", "mineral",
                "613", "613a", "royalty", "working interest"
            ],
            "intangible_drilling_costs": [
                "idc", "intangible drilling", "drilling costs", "263c",
                "expense drilling", "oil gas drilling"
            ],
            "qbi_deduction_199a": [
                "qbi", "199a", "qualified business income", "pass-through",
                "sstb", "20 percent", "w-2 wages"
            ],
            "child_tax_credit": [
                "child tax credit", "ctc", "additional child", "section 24",
                "qualifying child", "2000 per child"
            ],
            "earned_income_credit": [
                "eitc", "earned income", "eic", "refundable credit",
                "low income", "section 32"
            ],
            # New audit issue topics
            "hobby_loss_183": [
                "hobby", "hobby loss", "183", "profit motive", "not for profit",
                "nine factors", "presumption", "3 of 5"
            ],
            "worker_classification": [
                "employee", "contractor", "independent contractor", "1099",
                "w-2", "worker classification", "misclassification", "ss-8"
            ],
            "charitable_contributions": [
                "charitable", "donation", "charity", "contribution", "8283",
                "appraisal", "noncash", "acknowledgment", "overvaluation"
            ],
            "travel_entertainment": [
                "travel", "entertainment", "meals", "business travel",
                "per diem", "274", "substantiation", "away from home"
            ],
            "vehicle_mileage": [
                "vehicle", "mileage", "car", "auto", "280f", "standard mileage",
                "actual expense", "listed property", "commuting"
            ],
            "passive_activity_losses": [
                "passive", "passive activity", "469", "material participation",
                "pal", "suspended loss", "passive loss", "at risk"
            ],
            "like_kind_exchange_1031": [
                "1031", "like-kind", "like kind", "exchange", "starker",
                "qualified intermediary", "boot", "45 day", "180 day"
            ],
            "unreported_income_cash": [
                "unreported income", "cash business", "bank deposits",
                "net worth", "indirect method", "badges of fraud"
            ],
            "cryptocurrency_audit": [
                "crypto", "cryptocurrency", "bitcoin", "virtual currency",
                "digital asset", "mining", "staking", "coinbase"
            ],
            "fbar_fatca_foreign": [
                "fbar", "fatca", "foreign account", "8938", "fincen 114",
                "offshore", "foreign bank", "streamlined"
            ],
            "estimated_tax_penalty": [
                "estimated tax", "quarterly", "6654", "underpayment",
                "safe harbor", "annualized", "2210"
            ],
            "statute_of_limitations": [
                "statute", "limitations", "ased", "csed", "6501",
                "assessment", "collection", "expired", "tolling"
            ],
            "offer_in_compromise": [
                "offer in compromise", "oic", "656", "settle", "rcp",
                "doubt as to collectability", "fresh start"
            ],
            "innocent_spouse_relief": [
                "innocent spouse", "6015", "8857", "equitable relief",
                "separation of liability", "joint return"
            ],
            "trust_fund_recovery_penalty": [
                "trust fund", "6672", "responsible person", "tfrp",
                "payroll tax", "941", "withholding", "100 percent penalty"
            ],
            "depreciation_cost_segregation": [
                "depreciation", "cost segregation", "macrs", "179",
                "bonus depreciation", "168k", "accelerated", "27.5", "39 year"
            ],
            "rental_real_estate_losses": [
                "rental", "rental loss", "real estate professional",
                "750 hours", "active participation", "25000 allowance"
            ],
        }

        for topic, keywords in keyword_map.items():
            for kw in keywords:
                if kw not in self.keyword_index:
                    self.keyword_index[kw] = []
                self.keyword_index[kw].append(topic)

    def match_topic(self, query: str) -> Optional[str]:
        """Find best matching doctrine topic."""
        query_lower = query.lower()

        # Score each topic by keyword matches
        scores: Dict[str, int] = {}
        for keyword, topics in self.keyword_index.items():
            if keyword in query_lower:
                for topic in topics:
                    scores[topic] = scores.get(topic, 0) + len(keyword)

        if not scores:
            return None

        return max(scores, key=scores.get)

    def quick_answer(self, query: str) -> Optional[Tuple[str, str]]:
        """Get instant doctrine response. Returns (topic, answer) or None."""
        topic = self.match_topic(query)
        if topic and topic in self.cache:
            doctrine = self.cache[topic]
            return (doctrine.topic, doctrine.quick_answer)
        return None

    def full_doctrine(self, query: str) -> Optional[DoctrineResponse]:
        """Get complete doctrine with case law and playbook."""
        topic = self.match_topic(query)
        if topic and topic in self.cache:
            return self.cache[topic]
        return None

    def get_by_topic(self, topic_key: str) -> Optional[DoctrineResponse]:
        """Direct topic lookup."""
        return self.cache.get(topic_key)

    def list_topics(self) -> List[str]:
        """List all cached doctrine topics."""
        return [d.topic for d in self.cache.values()]


# Singleton instance
_engine = None

def get_engine() -> TaxDoctrineEngine:
    global _engine
    if _engine is None:
        _engine = TaxDoctrineEngine()
    return _engine

def quick_tax_answer(query: str) -> Optional[Tuple[str, str]]:
    """Instant doctrine lookup. Returns (topic, answer) or None."""
    return get_engine().quick_answer(query)

def full_tax_doctrine(query: str) -> Optional[DoctrineResponse]:
    """Complete doctrine with case law and audit playbook."""
    return get_engine().full_doctrine(query)


if __name__ == "__main__":
    engine = TaxDoctrineEngine()

    print("=" * 60)
    print("TAX DOCTRINE CACHE - FAST LOOKUP TEST")
    print("=" * 60)

    test_queries = [
        "How do I determine S-Corp reasonable compensation?",
        "IRS says profits are from ownership not labor",
        "What are the rules for percentage depletion on oil wells?",
        "Can I deduct my home office?",
        "What is the QBI deduction limit?",
    ]

    for q in test_queries:
        print(f"\nQuery: {q}")
        result = engine.quick_answer(q)
        if result:
            print(f"Topic: {result[0]}")
            print(f"Answer: {result[1][:150]}...")
        else:
            print("No doctrine match - would fall back to RAG")
